### ISSUE TITLE
Running instructions

### ISSUE THREAD

**Issue by IvanLjubicic** [SuyashMore/MevonAI-Speech-Emotion-Recognition#3]
Hi @SuyashMore 

Can you please tell me on which OS did you run this app? Because on Mac there is no 3.6.9 Python version to download.
Could you please provide some more detailed instructions to run it because there are a lot of compatibilities issues? 

Great job btw!

**Comment by SuyashMore** [comment]
Hello @IvanLjubicic 
I just tried the code on Python3.6.9 and it works fine. I have been using Ubuntu 18.04 to run the app although the code runs on macOS as well.

Heres the Demo Link:
https://colab.research.google.com/github/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/notebooks/Emotion_Recognition_Demo.ipynb

Instructions for Installation are mentioned here:
https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition#getting-started

All the Libraries required for the app are described in the setup script:
https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/setup.sh

If you face any compatibility issues, I would suggest you to install the libraries in a python virtual env.

Do let me know if you face any other issues or have any queries.Happy to help :D
