### ISSUE TITLE
tensorflow == 1.5.0 not supported on python>=3.8, request to upgrade tensorflow version >=2.5

### ISSUE THREAD

**Issue by paycall** [SuyashMore/MevonAI-Speech-Emotion-Recognition#5]
Hallo
I can not find tensorflow == 1.5.0 to ubuntu.
It may be possible to arrange the installation and activation of the software tensorflow == 2.5.0

**Comment by SuyashMore** [comment]
Workarounds:
- downgrade to python<=3.7 

- Alternatively try  https://stackoverflow.com/questions/62519844/installing-tensorflow-1-15

**Comment by SuyashMore** [comment]
> It may be possible to arrange the installation and activation of the software tensorflow == 2.5.0

tuch kar

**Comment by paycall** [comment]
Hello

I'm running speechEmotionRecognition.py using pipenv as follows:

pipenv run python -v -d speechEmotionRecognition.py

I get Illegal instruction. I have attached the full output, and it seems
that something is wrong with tensorflow.

Am I missing something?



‫בתאריך יום א׳, 23 במאי 2021 ב-11:46 מאת ‪Suyash More‬‏ <‪
***@***.***‬‏>:‬

**Comment by paycall** [comment]
[output.zip](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/files/6539314/output.zip)

**Comment by Oliver4an** [comment]
colud  this project work in m1 chip?

**Comment by SuyashMore** [comment]
I see no reason why it cannot. Works on google colab if you are unable to
run it on local

**Comment by chinmaynehate** [comment]
To solve the issue regarding dependencies, I've created a [Dockerfile](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/Dockerfile).

Please follow [the method 1, which I've upadated in the readme](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/README.md#method-1), to run the application.
