### ISSUE TITLE
The right versions of all dependencies

### ISSUE THREAD

**Issue by DavideDeodati** [SuyashMore/MevonAI-Speech-Emotion-Recognition#8]
I wanted to try to use this project for a university thesis but I can't get it started. I can't find the right combinations of all the python versions. I have tried various setup.sh combos but can't get out of it. Can you tell me exactly the versions of each component needed to get it started?

**Comment by chinmaynehate** [comment]
Hi @DavideDeodati,

Thanks for checking out this project.

Versions:
Python: 3.6.9
pip: 21.3.1
TensorFlow: 1.15
PyTorch: 1.5.0
PyAudio: 0.2.13

To solve the issue regarding dependencies, I've created a [Dockerfile](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/Dockerfile).

Please follow [the method 1, which I've upadated in the readme](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/README.md#method-1) to run the application.

Thanks,
Chinmay

**Comment by chinmaynehate** [comment]
Hi @DavideDeodati,

Thanks for checking out this project.

Versions:
Python: 3.6.9
pip: 21.3.1
TensorFlow: 1.15
PyTorch: 1.5.0
PyAudio: 0.2.13

To solve the issue regarding dependencies, I've created a [Dockerfile](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/Dockerfile).

Please follow [the method 1, which I've upadated in the readme](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/README.md#method-1), to run the application.

Thanks,
Chinmay

**Comment by chinmaynehate** [comment]
Hi @DavideDeodati,

The versions for all the libraries can be found in [requirements.txt](https://github.com/SuyashMore/MevonAI-Speech-Emotion-Recognition/blob/master/src/requirements.txt)

Thanks,
Chinmay

**Comment by chinmaynehate** [comment]
Reopen if you still face any issues.
